[SERVICE]
    Flush         1
    Log_Level     info
    Daemon        off

[INPUT]
    Name                  winevtlog
    Channels              Microsoft-Windows-Sysmon/Operational
    Interval_Sec          1
    Read_Existing_Events  false

[FILTER]
    Name    modify
    Match   *
    Remove  StringInserts

[OUTPUT]
    Name               opensearch
    Match              *
    Host               192.168.56.1
    Port               9200
    HTTP_User          admin
    HTTP_Passwd        CHANGEME_OPENSEARCH_ADMIN_PASSWORD
    tls                On
    tls.verify         Off
    Suppress_Type_Name On
    Trace_Error        On
    Index              sysmon-logs
    Logstash_Format    Off
